# MongoDB Exporter — Prometheus가 MongoDB 메트릭을 수집할 수 있도록 변환
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  namespace: playcode
  labels:
    app: mongodb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
    spec:
      containers:
        - name: mongodb-exporter
          image: percona/mongodb_exporter:0.40
          args:
            - --mongodb.uri=mongodb://admin:$(MONGO_PASSWORD)@mongodb-service:27017/admin
            - --collect-all
            - --compatible-mode
          env:
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: playcode-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD
          ports:
            - containerPort: 9216
              name: metrics
          resources:
            requests:
              memory: "32Mi"
              cpu: "25m"
            limits:
              memory: "64Mi"
              cpu: "50m"
          livenessProbe:
            httpGet:
              path: /
              port: 9216
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  namespace: playcode
  labels:
    app: mongodb-exporter
spec:
  selector:
    app: mongodb-exporter
  ports:
    - port: 9216
      targetPort: 9216
      name: metrics
  type: ClusterIP

---
# Prometheus가 MongoDB Exporter를 자동 탐색
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb-exporter-monitor
  namespace: playcode
  labels:
    app: mongodb-exporter
    release: prometheus
spec:
  selector:
    matchLabels:
      app: mongodb-exporter
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
