# Redis Exporter — Prometheus가 Redis 메트릭을 수집할 수 있도록 변환
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: playcode
  labels:
    app: redis-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
        - name: redis-exporter
          image: oliver006/redis_exporter:v1.58.0-alpine
          args:
            - --redis.addr=redis://redis-service:6379
          ports:
            - containerPort: 9121
              name: metrics
          resources:
            requests:
              memory: "16Mi"
              cpu: "15m"
            limits:
              memory: "32Mi"
              cpu: "25m"
          livenessProbe:
            httpGet:
              path: /health
              port: 9121
            initialDelaySeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: playcode
  labels:
    app: redis-exporter
spec:
  selector:
    app: redis-exporter
  ports:
    - port: 9121
      targetPort: 9121
      name: metrics
  type: ClusterIP

---
# Prometheus가 Redis Exporter를 자동 탐색
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter-monitor
  namespace: playcode
  labels:
    app: redis-exporter
    release: prometheus
spec:
  selector:
    matchLabels:
      app: redis-exporter
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
